language: objective-c

before_install:
 # Make sure mono is installed,
 - wget http://download.mono-project.com/archive/3.0.10/macos-10-x86/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
 - hdid MonoFramework-MDK-3.0.10.macos10.xamarin.x86.dmg
 - sudo installer -pkg "/Volumes/Mono Framework MDK 3.0.10/MonoFramework-MDK-3.0.10.macos10.xamarin.x86.pkg" -target /

install:
 - xbuild XHelloWorld.sln

#  language: objective-c

# env:
#  global:
#   - EnableNuGetPackageRestore=true
#  matrix:
#   - MONO_VERSION="3.4.0"
# before_install:
#  - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
#  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
#  - .ci/travis/nuget-restore.sh Mobile.sln
# script:
#  - xbuild /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true /target:Build XHelloWorld.sln

#  language: csharp

# solution: XHelloWorld.sln

# # script:
# # - xbuild /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true /target:Build XHelloWorld.sln

